---
# https://kubernetes.io/docs/concepts/policy/pod-security-policy/
apiVersion: v1
kind: List
items:

- apiVersion: rbac.authorization.k8s.io/v1  
  kind: RoleBinding
  metadata:
    name: z-rb-psp-run-as-any
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: psp:run-as-any
  subjects:
  - kind: ServiceAccount
    namespace: staranto 
    name: z-sa-weak
...
