---
apiVersion: v1
kind: List
items:

- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata:
    name: pc-high
  value: 1000000

- apiVersion: scheduling.k8s.io/v1
  kind: PriorityClass
  metadata:
    name: pc-low
  value: 800000

...
