---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: e-targeted-deploy
  name: e-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      taranto.dev/example: e-dep
  template:
    metadata:
      labels:
        taranto.dev/example: e-dep
    spec:
      nodeSelector:
        # NVIDIA GPU passthrough
        feature.node.kubernetes.io/pci-10de.present: "true"
      containers:
      - name: e-one
        image: bash
        command: [ "top" ]
...
