---
apiVersion: rbac.authorization.k8s.io/v1  
kind: RoleBinding
metadata:
  name: z-sa-rolebinding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: z-list-pods
subjects:
- kind: ServiceAccount
  name: z-sa
...
