---
apiVersion: v1
kind: List
items:

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: z-get-rsh-pods
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
  - apiGroups:
    - ""
    resources:
    - pods/exec
    verbs:
    - create

- apiVersion: rbac.authorization.k8s.io/v1  
  kind: RoleBinding
  metadata:
    name: z-get-rsh-pods
  roleRef:
    kind: Role
    apiGroup: rbac.authorization.k8s.io
    name: z-get-rsh-pods
  subjects:
  - kind: ServiceAccount
    name: z-sa

...
