kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: c-rolebinding-zach
  namespace: k8s-demo
subjects:
- kind: ServiceAccount
  name: zach
  namespace: k8s-demo
  # apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: c-role-zach
  apiGroup: rbac.authorization.k8s.io

