---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: b-pv
spec:
  capacity:
    storage: 5Gi
  nfs:
    server: www.0.taranto.dev
    path: /srv/nfs
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
...
