---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  storageClassName: sc-1
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  iscsi:
     targetPortal: 192.168.86.247:3260
     iqn: iqn.2020-08.dev.taranto:ocpk-test
     lun: 0
     fsType: 'ext4'
...
