apiVersion: v1
kind: PersistentVolume
metadata:
  name: b-pv
  labels:
    type: local
spec:
  storageClassName: b-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/kube"

