---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: a-dep
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
spec:
  replicas: 3
  selector:
    matchLabels:
      taranto.dev/example: a-dep
  template:
    metadata:
      labels:
        taranto.dev/example: a-dep
    spec:
      containers:
      - name: a-one
        image: staranto/k8s-demo-runner:latest
        imagePullPolicy: Always
      terminationGracePeriodSeconds: 0
...
