---
kind: Pod
apiVersion: v1
metadata:
  name: a-pod
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: a-core
spec:
  containers:
  - name: a-one
    image: staranto/k8s-demo-runner:latest
    imagePullPolicy: Always
  terminationGracePeriodSeconds: 1

...
