---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: b-pv
  annotations:
    pv.beta.kubernetes.io/gid: '2049'
  deletionGracePeriodSeconds: 0
spec:
  capacity:
    storage: 512Mi
  nfs:
    server: fs-a8a600d0.efs.us-east-2.amazonaws.com
    path: /b-pv
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: b-sc
  mountOptions:
    - vers=4.1
  volumeMode: Filesystem
...
