---
apiVersion: v1
kind: ConfigMap
metadata:
  name: b-cm-efs-provisioner
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: b-storage
data:
  file.system.id: fs-40c2d139 
  aws.region: us-east-2
  provisioner.name: openshift.org/aws-efs
...
--- 
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: b-cr-efs-provisioner-runner
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: b-storage
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "update", "patch"]
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    verbs: ["use"]
    resourceNames: ["hostmount-anyuid"]
...
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: b-crb-efs-provisioner
  labels:
    taranto.dev/app: k8s-demo
    taranto.dev/section: b-storage
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: staranto
roleRef:
  kind: ClusterRole
  name: b-cr-efs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
...
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: b-r-leader-locking-efs-provisioner
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
...
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: b-rb-leader-locking-efs-provisioner
subjects:
  - kind: ServiceAccount
    name: efs-provisioner
    namespace: staranto
roleRef:
  kind: Role
  name: b-r-leader-locking-efs-provisioner
  apiGroup: rbac.authorization.k8s.io
...
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: b-sc
provisioner: openshift.org/aws-efs
parameters:
  gidMin: "2048" 
  gidMax: "2147483647" 
  gidAllocate: "true"
reclaimPolicy: Retain
...
---
kind: Pod
apiVersion: v1
metadata:
  name: b-efs-provisioner
spec:
  serviceAccount: efs-provisioner
  containers:
    - name: efs-provisioner
      image: quay.io/external_storage/efs-provisioner:latest
      env:
        - name: PROVISIONER_NAME
          valueFrom:
            configMapKeyRef:
              name: b-cm-efs-provisioner
              key: provisioner.name
        - name: FILE_SYSTEM_ID
          valueFrom:
            configMapKeyRef:
              name: b-cm-efs-provisioner
              key: file.system.id
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: b-cm-efs-provisioner
              key: aws.region
        - name: DNS_NAME
          valueFrom:
            configMapKeyRef:
              name: b-cm-efs-provisioner
              key: dns.name
              optional: true
      volumeMounts:
        - name: pv-volume
          mountPath: /persistentvolumes
  volumes:
    - name: pv-volume
      nfs:
        server: fs-a8a600d0.efs.us-east-2.amazonaws.com 
        path: / 
...
